### ISSUE TITLE
[Story] Set up Tech Stack

### ISSUE THREAD

**Issue by brandon1202h** [ntmack1/Fish-Finder----SE-491-Spring-2024#10]
Story Points: 10

Download and set-up these technologies with your IDE of your choice: 

-  React JS
- Java
- Bootstrap 5
- Postgresql
- Git
- Clone GitHub Repo
### Done: 

- [x] Wasif
- [x] Nathan
- [x] Brandon
- [x] Nikhil
- [x] Pritiv

**Comment by brandon1202h** [comment]
I just finished downloading and setting up the tech stack for my system.

**Comment by nmeda18** [comment]
@brandon1202h  can you add me in this task as well?, please. 
@Wasif20 @ntmack1 @pritiv21 FYI

**Comment by nmeda18** [comment]
Downloaded and Setup have been completed
