### ISSUE TITLE
[Story] Profile Creation

### ISSUE THREAD

**Issue by brandon1202h** [ntmack1/Fish-Finder----SE-491-Spring-2024#8]
Story Point: 10

Create the profile page of the user. For this sprint, it will be bare bones and more of a concept. In feature sprints we will be adding things such as favoriting fish adding profile pictures etc.

**Comment by ntmack1** [comment]
Downgraded to just a 5 point story. For now, this profile page only has minimal functionality. Will add another story to add more features in future sprint.
